[package]
name = "Hellow"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
hyper = { version = "1.4.1" , features=["full"] }
serde = { version = "1.0.210" , features=["derive"] }
tera = "1.20.0"
tokio = { version = "1.40.0" , features=["full"] }
